import assert from 'node:assert/strict';
import {niches,languages,localizedQuery,matchesKeywords,evidence,defaultWeights,shortlistCSV} from '../dist/research-core.js';
const fi={country:'FI',language:'fi',niche:'Budget gaming',goal:'buyers'};
assert.match(localizedQuery(fi),/halpa pelikone/);
assert.match(localizedQuery({...fi,language:'de'}),/günstiger/);
assert.match(localizedQuery({...fi,niche:'Upgrading & reselling'}),/päivitys/);
assert.match(localizedQuery(fi),/"halpa pelikone"/);
for(const language in languages)for(const niche of niches){const q=localizedQuery({language,niche});assert.ok(q.length<=220,q);assert.equal(q.split('|').length,5,q);assert.equal((q.match(/"/g)||[]).length%2,0,q)}
assert.notEqual(localizedQuery({language:'sv',niche:'Gaming'}),localizedQuery({language:'sv',niche:'Budget gaming'}));
const topic=(title,niche)=>evidence({followers:1,videos:[{title,description:''}]},{...fi,niche}).factors.topic;
assert.equal(topic('My latest contest, the fastest speedrun','PC performance'),0);
assert.equal(topic('I focused on what caused the bug','Refurbished tech'),0);
assert.equal(topic('Kasaan elämäni parhaan kakun','PC building'),0);
assert.equal(topic('Sellaista elämää','Upgrading & reselling'),0);
assert.equal(topic('Uppgraderar min gamla speldator','Upgrading & reselling'),100);
assert.equal(topic('Bästa PC-spel 2026','Gaming'),100);
assert.equal(topic('RTX 5060 i en billig gamingdator','Gaming'),100);
assert.equal(topic('Min semester i Spanien','Gaming'),0);
assert.equal(topic('RTX 4060 benchmark test','PC performance'),100);
assert.equal(topic('Used gaming PC for 300€','Refurbished tech'),100);
assert.equal(topic('Kasasin budjettipelikoneen','PC building'),100);
assert.equal(topic('Uusi budjettipelikone','Gaming'),100);
assert.ok(matchesKeywords('Günstiger Gaming-PC',['günstig']));
const c={name:'=SYNTHETIC TEST',sourceType:'imported',platform:'Twitch',followers:1000,videos:[{title:'halpa pelikone testi',description:'budget test',views:500,likes:null,comments:4,publishedAt:'2026-09-01T00:00:00Z',language:null,url:'https://twitch.tv/synthetic_test_only'}]};
const e=evidence(c,fi,defaultWeights,Date.parse('2026-09-26'));
assert.equal(e.factors.topic,100);assert.equal(e.factors.language,null);assert.equal(e.factors.engagement,null);assert.equal(e.factors.views,50);assert.equal(e.factors.reach,23);assert.equal(e.known,4);assert.equal(e.total,6);
const reach=views=>evidence({followers:1,videos:[{title:'',views}]},fi).factors.reach;
assert.equal(reach(50),0);assert.equal(reach(1000),33);assert.equal(reach(10000),67);assert.equal(reach(2000000),100);
assert.equal(evidence(c,fi,{topic:40,language:20,recency:15,views:15,engagement:10}).score!==null,true);
assert.equal(evidence(c,fi,Object.fromEntries(Object.keys(defaultWeights).map(k=>[k,0]))).score,null);
assert.equal(evidence({...c,followers:null},fi).factors.views,null);
const csv=shortlistCSV([{creator:c,pipeline:{status:'Shortlisted',notes:'first line\nsecond, line',review:'Reviewing'}}],fi,defaultWeights);
const [header]=csv.split('\r\n');assert.ok(header.includes('reach_score'));
assert.match(csv,/'=SYNTHETIC TEST/);assert.match(csv,/Audience geography unverified/);assert.match(csv,/first line\nsecond, line/);
console.log('Core checks passed: localized queries, missing evidence, scoring, zero weights, CSV escaping.');
