import assert from 'node:assert/strict';
import {localizedQuery,matchesKeywords,evidence,defaultWeights,shortlistCSV} from '../dist/research-core.js';
const fi={country:'FI',language:'fi',niche:'Budget gaming',goal:'buyers'};
assert.match(localizedQuery(fi),/halpa pelikone/);
assert.match(localizedQuery({...fi,language:'de'}),/günstiger/);
assert.match(localizedQuery({...fi,goal:'sellers'}),/myynti/);
assert.equal(localizedQuery(fi),'"halpa pelikone" | "budjetti pelitietokone"');
const topic=(title,niche,goal='buyers')=>evidence({followers:1,videos:[{title,description:''}]},{...fi,niche,goal}).factors.topic;
assert.equal(topic('My latest contest, the fastest speedrun','PC performance'),0);
assert.equal(topic('I focused on what caused the bug','Refurbished tech'),0);
assert.equal(topic('Kasaan elämäni parhaan kakun','PC building'),0);
assert.equal(topic('Sellaista elämää','Gaming','sellers'),0);
assert.equal(topic('RTX 4060 benchmark test','PC performance'),100);
assert.equal(topic('Used gaming PC for 300€','Refurbished tech'),100);
assert.equal(topic('Kasasin budjettipelikoneen','PC building'),100);
assert.equal(topic('Uusi budjettipelikone','Gaming'),100);
assert.ok(matchesKeywords('Günstiger Gaming-PC',['günstig']));
const c={name:'=SYNTHETIC TEST',sourceType:'imported',platform:'Twitch',followers:1000,videos:[{title:'halpa pelikone testi',description:'budget test',views:500,likes:null,comments:4,publishedAt:'2026-09-01T00:00:00Z',language:null,url:'https://twitch.tv/synthetic_test_only'}]};
const e=evidence(c,fi,defaultWeights,Date.parse('2026-09-26'));
assert.equal(e.factors.topic,100);assert.equal(e.factors.language,null);assert.equal(e.factors.engagement,null);assert.equal(e.factors.views,50);assert.equal(e.known,3);
assert.equal(evidence(c,fi,Object.fromEntries(Object.keys(defaultWeights).map(k=>[k,0]))).score,null);
assert.equal(evidence({...c,followers:null},fi).factors.views,null);
const csv=shortlistCSV([{creator:c,pipeline:{status:'Shortlisted',notes:'first line\nsecond, line',review:'Reviewing'}}],fi,defaultWeights);
assert.match(csv,/'=SYNTHETIC TEST/);assert.match(csv,/Audience geography unverified/);assert.match(csv,/first line\nsecond, line/);
console.log('Core checks passed: localized queries, missing evidence, scoring, zero weights, CSV escaping.');
